server:
  port: 8888
spring:
  redis:
    host: 47.92.132.207
    port: 6379
    password: 123456
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://47.92.132.207:3306/mj_erp?useUnicode=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mapper:
  identity: MYSQL
