server:
  port: 8888
spring:
  redis:
    host: 81.69.194.36
    port: 6379
    password: 123456
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://81.69.194.36:3306/saas?useUnicode=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mapper:
  identity: MYSQL
